### ISSUE TITLE
chef_gem's compile_time property must only be set if it is available

### ISSUE THREAD

**Issue by sunruh** [opscode-cookbooks/chef-vault#21]
Instead of just setting the property, it should be checked whether it is available on the resource for backwards compatibility. Compare [Chef 12.1.0 chef_gem resource warnings, section "Community Cookbooks"](https://www.chef.io/blog/2015/02/17/chef-12-1-0-chef_gem-resource-warnings/).

[recipes/default.rb L23 ](https://github.com/opscode-cookbooks/chef-vault/blob/master/recipes/default.rb#L23) and [test/fixtures/cookbooks/test/recipes/chef_vault_secret.rb L33](https://github.com/opscode-cookbooks/chef-vault/blob/master/test/fixtures/cookbooks/test/recipes/chef_vault_secret.rb#L33) should read
```ruby
  compile_time true if respond_to?(:compile_time)
```

**Comment by someara** [comment]
Sorry about that. Fixed in the latest patch release

**Comment by sunruh** [comment]
Things happen. Thanks for the quick fix.

**Comment by martinisoft** [comment]
This is still broken for me, On chef 11.16.4

```
  ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/chef-vault/recipes/default.rb
  ================================================================================

  ArgumentError
  -------------
  wrong number of arguments (1 for 0)

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/chef-vault/recipes/default.rb:23:in `block in from_file'
    /var/chef/cache/cookbooks/chef-vault/recipes/default.rb:21:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/chef-vault/recipes/default.rb:

   16:  # distributed under the License is distributed on an "AS IS" BASIS,
   17:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   18:  # See the License for the specific language governing permissions and
   19:  # limitations under the License.
   20:
   21:  chef_gem 'chef-vault' do
   22:    version node['chef-vault']['version']
   23>>   compile_time true if respond_to?(:compile_time)
   24:  end
   25:
   26:  require 'chef-vault'
   27:


  Running handlers:
  Running handlers complete
  Chef Client failed. 0 resources updated in 20.247337875 seconds
```

**Comment by sunruh** [comment]
@martinisoft Could you provide a Stacktrace leading to the error?

You should see something like `FATAL: Stacktrace dumped to ...` in the chef output, telling you where to find it.

**Comment by martinisoft** [comment]
@sunruh Seems this was rolled back already and I don't have the log handy anymore. Apologies for that.
