### ISSUE TITLE
Testing a cookbook that uses chef-vault in test-kitchen and chef-zero

### ISSUE THREAD

**Issue by iroller** [opscode-cookbooks/chef-vault#23]
> moved from https://github.com/Nordstrom/chef-vault/issues/146

Trying to create some tests in test-kitchen for a cookbook that uses chef-vault. The cookbook actually executes `ChefVault::Item.load(...)`. So I need to create that vault item in my test recipe.

I found [chef_vault_item](https://github.com/opscode-cookbooks/chef-vault/blob/master/libraries/chef_vault_item.rb) lwrp and trying to use it to create new vault:

```
chef_vault_secret 'testitem' do
  data_bag 'testbag'
  admins 'hello-world-ubuntu-1204'
  raw_data({ key: 'data' })
  search '*:*'
  action :nothing
end.run_action(:create)

include_recipe "my-cookbook-to-test"
```

However it fails with 
```
ChefVault::Exceptions::AdminNotFound
------------------------------------
FATAL: Could not find hello-world-ubuntu-1204 in users or clients!
```

And there're actually no clients or users in chef-zero:
```
root@5a51fe47d4ca:~# knife client list -c /tmp/kitchen/client.rb -z

root@5a51fe47d4ca:~# knife user list -c /tmp/kitchen/client.rb -z

root@5a51fe47d4ca:~# knife node list -c /tmp/kitchen/client.rb -z
hello-world-ubuntu-1204
```

Any ideas on how to work it around?

**Comment by jtimberman** [comment]
You need to add the appropriate fixtures to your cookbook. For example, the chef-vault cookbook itself tests the LWRP with a 'hydroelectric' client

- https://github.com/opscode-cookbooks/chef-vault/tree/master/test/integration/clients
- https://github.com/opscode-cookbooks/chef-vault/tree/master/test/integration/nodes
- https://github.com/opscode-cookbooks/chef-vault/blob/master/test/fixtures/cookbooks/test/recipes/chef_vault_secret.rb#L40

**Comment by iroller** [comment]
Got it, thanks!

**Comment by Fitzsimmons** [comment]
The first two links are 404ing now. Can you update this post for other people like me who are finding this through searching?

**Comment by iroller** [comment]
Those were moved into fixtures. See .kitchen.yml:
https://github.com/chef-cookbooks/chef-vault/blob/d9961507a629bf6619780f399c73fa90546b7a5c/.kitchen.yml#L6-L7
