### ISSUE TITLE
ChefSpec mock not working after switching to chef-vault cookbook

### ISSUE THREAD

**Issue by dgoradia-atlas** [opscode-cookbooks/chef-vault#29]
I was using the chef-vault gem prior but after switching to the chef-vault cookbook I changed my code to

    chef_vault_item('encrypted', 'item')

from 

    ChefVault::Item.load('encrypted', 'item')

In my spec file I have:

    allow(ChefVault::Item).to receive(:load).with('encrypted', 'item').and_return({..})

This was working fine with `ChefVault::Item.load` but no longer works with `chef_vault_item`. Is there another was I'm supposed to stub the data bag?

**Comment by mhenrixon** [comment]
I am experiencing the same problem see my gist for more information -> https://gist.github.com/mhenrixon/6a85eb74988b43dfdfdd

What is your error?

**Comment by dgoradia-atlas** [comment]
I ended up using the [chef-vault-testfixtures](https://github.com/Nordstrom/chef-vault-testfixtures) gem but I've encountered a bug on that: [#11](https://github.com/Nordstrom/chef-vault-testfixtures/issues/11)

**Comment by dgoradia-atlas** [comment]
@mhenrixon @jf647 has fixed bug [#11](https://github.com/Nordstrom/chef-vault-testfixtures) and released 0.5.0. This should work for you.
